---
Name: mysite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'garabatos'

Member:
  extensions:
    - MemberExtend

Article:
  extensions:
    - Linkable
    
Product:
  extensions:
    - Linkable

Image:
  extensions:
    - GrayscaleDecorator
    
Director:
  environment_type: 'dev'

Collection:
  extensions:
    - Linkable


BetterButtonsActions:
  create:
    Button_SaveAndAdd: true
    Button_Save: true
    Button_SaveAndClose: true