---
Name: customroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'search/$ID' : 'Search_Controller'
    'collection' : 'CollectionsPage_Controller'
    'products/$URLSegment'  : 'Product_Controller'
    'blankimage/$width/$height'  : 'BlankImage_Controller'